<?php

/**
 * tzMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tzMapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tzMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tzMap');
    }
}